services:
  tunneldock:
    build: .
    container_name: tunneldock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped